/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard1;
import dashboard1.BankSystem;
import dashboard1.Login;
import dashboard1.SignUp;
import dashboard1.NewPassword;
import java.sql.SQLException;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Moemen Mohamed
 */

public class forgotPassword extends javax.swing.JFrame {
    /**
     * Creates new  security_questions
    */
    int first,second;
    public forgotPassword() throws SQLException {
        initComponents();
        Random rand=new Random(System.currentTimeMillis());
        first=rand.nextInt(2);
        second=rand.nextInt(2);
        while(first==second)second=rand.nextInt(2);
        firstQuestion1.setText(dashboard1.BankSystem.security[first]);
        secondQuestion.setText(dashboard1.BankSystem.security[second]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new dashboard1.GrandientPanel();
        jPanel1 = new javax.swing.JPanel();
        firstQuestion = new javax.swing.JLabel();
        jPanel22 = new dashboard1.GrandientPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JFormattedTextField();
        secondQuestion = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        firstQuestion1 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel21.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel21.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstQuestion.setForeground(new java.awt.Color(51, 204, 255));
        firstQuestion.setText("Email");
        jPanel1.add(firstQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 480, 30));

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel22.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                                            SUBMIT");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 50));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 520, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 255));
        jLabel25.setText("                    ANSWER  SECURITY QUESTIONS");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 480, 60));

        inputEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        inputEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputEmailKeyReleased(evt);
            }
        });
        jPanel1.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 490, 30));

        secondQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondQuestion.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.add(secondQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 500, 30));

        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        jFormattedTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 490, 20));

        firstQuestion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstQuestion1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.add(firstQuestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 480, 30));

        jFormattedTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jFormattedTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 490, 20));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 720, 460));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Understanding Customers And Make their life Easy With One Click");
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 770, 110));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/53620-200.png")); // NOI18N
        jLabel2.setText("     Maze Bank");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("       Banking Software");
        jPanel21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 280, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Bankeeeeeeeees.png")); // NOI18N
        jPanel21.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 550, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 1391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

int count=3;
String inputemail=null;
String inputString=null,inputString1=null;
static dashboard1.BankSystem.Client client=null;
String answer1=null,answer2=null;
NewPassword newPass=new NewPassword();

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.out.println(inputemail);
        answer1=client.getSecurity(first);
        answer2=client.getSecurity(second);
//        System.out.println(answer1);
//        System.out.println(answer2);
//        System.out.println(inputString);
//        System.out.println(inputString1);
//        System.out.println(answer2.equalsIgnoreCase(inputString1));
//        System.out.println(answer1.equalsIgnoreCase(inputString));
//        
        if(client==null){
           JOptionPane.showMessageDialog(null, "Account Not Found"); 
        }
        if(!answer2.equalsIgnoreCase(inputString1) || !answer1.equalsIgnoreCase(inputString)){
           JOptionPane.showMessageDialog(null, "The answeres doesn't match try again");
           count--;
        }
        if(count==0){
            JOptionPane.showMessageDialog(null, "We Have Blocked The Account Contact With Us");
            try {
                dashboard1.BankSystem.bank.serverAdmin.server.UpdateState(client.getAccountNumber());
            } catch (SQLException ex) {
                Logger.getLogger(forgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(answer2.equalsIgnoreCase(inputString1) && answer1.equalsIgnoreCase(inputString)){
           newPass.setVisible(true);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jFormattedTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField4KeyReleased
        inputString=jFormattedTextField4.getText();
    }//GEN-LAST:event_jFormattedTextField4KeyReleased

    private void inputEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEmailKeyReleased
        inputemail=inputEmail.getText();
        try {
            client=dashboard1.BankSystem.bank.serverAdmin.server.queryClient(inputemail);
        } catch (SQLException ex) {
            Logger.getLogger(forgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputEmailKeyReleased

    private void jFormattedTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField3KeyReleased
        inputString1=jFormattedTextField3.getText();
    }//GEN-LAST:event_jFormattedTextField3KeyReleased

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new forgotPassword().setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(forgotPassword.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstQuestion;
    private javax.swing.JLabel firstQuestion1;
    private javax.swing.JFormattedTextField inputEmail;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private dashboard1.GrandientPanel jPanel21;
    private dashboard1.GrandientPanel jPanel22;
    private javax.swing.JLabel secondQuestion;
    // End of variables declaration//GEN-END:variables
}
