/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard1;
import dashboard1.SignUp;
import dashboard1.forgotPassword;
import dashboard1.BankSystem;
import dashboard1.BankSystem.TransactionDetails;
import dashboard1.MainPage;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import dashboard1.appendSecurity;
import javax.swing.JOptionPane;
/**
 *
 * @author Moemen Mohamed
 */
public class Login extends javax.swing.JFrame {
    static String Email=null,Password=null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new dashboard1.GrandientPanel();
        jPanel1 = new javax.swing.JPanel();
        LableEmail = new javax.swing.JLabel();
        InputEmail = new javax.swing.JTextField();
        Pass = new javax.swing.JLabel();
        jPanel22 = new dashboard1.GrandientPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JLabel();
        HidePassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel21.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LableEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LableEmail.setForeground(new java.awt.Color(51, 204, 255));
        LableEmail.setText("Email");
        jPanel1.add(LableEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, 20));

        InputEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        InputEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InputEmailKeyPressed(evt);
            }
        });
        jPanel1.add(InputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 510, 20));

        Pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(51, 204, 255));
        Pass.setText("Password");
        jPanel1.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 80, 20));

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel22.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                                            LOGIN");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, 50));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 530, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 255));
        jLabel25.setText("                    LOGIN");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 240, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Don't have an account ? ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SignUp");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Forgot Password?");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 120, -1));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 510, 20));

        ShowPassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Showbobo.jpg")); // NOI18N
        ShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 50, 30));

        HidePassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/UnshowPassBlue.jpg")); // NOI18N
        HidePassword.setText("jLabel3");
        HidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HidePasswordMouseClicked(evt);
            }
        });
        jPanel1.add(HidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 50, 30));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 730, 450));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html> Understanding Customers  And Make their life Easy With One Click </br> </html>");
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 800, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images\\53620-200.png")); // NOI18N
        jLabel2.setText("   Maze Bank");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("        Banking Software");
        jPanel21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 280, 40));

        jLabel7.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/Moemen%20Mohamed/Documents/NetBeansProjects/Dashboard1/test/Images/Bankeeeeeeeees.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel21.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 550, 510));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -1, 1510, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static SignUp Signup;
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        try {
            Signup=new SignUp();
            Signup.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new forgotPassword().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void InputEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputEmailKeyPressed
        Email=InputEmail.getText();        
    }//GEN-LAST:event_InputEmailKeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
         Password=new String(jPasswordField1.getPassword()); 
    }//GEN-LAST:event_jPasswordField1KeyPressed
    int count=0; 
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
        BankSystem.bank.customer=BankSystem.bank.serverAdmin.server.queryClient(Email);
        if(BankSystem.bank.customer==null)JOptionPane.showMessageDialog(null, "We Couldn't Found Your Account.");
        if(BankSystem.bank.serverAdmin.server.queryState(BankSystem.bank.customer.getAccountNumber())==1){
                JOptionPane.showMessageDialog(null, "The Account Is Blocked Contact With US.");
                return;
        }
        if(BankSystem.bank.customer!=null){
            Password=new String(jPasswordField1.getPassword());
            String db_password=BankSystem.bank.customer.getPass();
            if(db_password.equals(BankSystem.bank.systemAdmin.system.encryptPassword(Password))){
                setVisible(false);
                MainPage object=new MainPage();
//                BankSystem.bank.customer.customers=new dashboard1.BankSystem().new TransactionDetails();
                object.setVisible(true);
            }else{
                if(count<3){
                    jPasswordField1.setText("");
                    JOptionPane.showMessageDialog(null, "Wrong Password Try Again.");
                    count+=1;
                }
                else{BankSystem.bank.serverAdmin.server.UpdateState(BankSystem.bank.customer.getAccountNumber());
                JOptionPane.showMessageDialog(null, "We Have Blocked The Account Contact With US.");
                }
            }
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordMouseClicked
        HidePassword.setVisible(true);
        jPasswordField1.setEchoChar((char)0);
        ShowPassword.setVisible(false);
    }//GEN-LAST:event_ShowPasswordMouseClicked

    private void HidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePasswordMouseClicked
        HidePassword.setVisible(false);
        jPasswordField1.setEchoChar('\u2022');
        ShowPassword.setVisible(true);
    }//GEN-LAST:event_HidePasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HidePassword;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JLabel LableEmail;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel ShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private dashboard1.GrandientPanel jPanel21;
    private dashboard1.GrandientPanel jPanel22;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
