/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard1;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import dashboard1.BankSystem;
import dashboard1.Login;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Moemen Mohamed
 * 
 */
public class MainPage extends javax.swing.JFrame {

    /**
     */
//    public NewJFrame1() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new dashboard1.GrandientPanel();
        Dashboard = new javax.swing.JLabel();
        Withdraw = new javax.swing.JLabel();
        Deposite = new javax.swing.JLabel();
        Loan = new javax.swing.JLabel();
        DeleteAccount = new javax.swing.JLabel();
        ProfileName = new javax.swing.JLabel();
        UpdateAccount = new javax.swing.JLabel();
        subPanel = new javax.swing.JPanel();
        UpdateEmail = new javax.swing.JLabel();
        UpdatePassword = new javax.swing.JLabel();
        UpdateAdress = new javax.swing.JLabel();
        UpdatePhone = new javax.swing.JLabel();
        grandientPanel11 = new dashboard1.GrandientPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Main = new javax.swing.JTabbedPane();
        MainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TransactionHistory = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        ShowPassword = new javax.swing.JLabel();
        HidePassword = new javax.swing.JLabel();
        JD2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        AccountBalance = new javax.swing.JLabel();
        AccountNumber = new javax.swing.JLabel();
        AccountType = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        Amount = new javax.swing.JLabel();
        InputAmount = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        grandientPanel1 = new dashboard1.GrandientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        Amount1 = new javax.swing.JLabel();
        InputAmount1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        grandientPanel2 = new dashboard1.GrandientPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LoanL = new javax.swing.JLabel();
        Loan1 = new javax.swing.JTextField();
        Lona2 = new javax.swing.JTextField();
        LoanLabel = new javax.swing.JLabel();
        grandientPanel8 = new dashboard1.GrandientPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        NewEmail = new javax.swing.JLabel();
        InputNewEmail = new javax.swing.JTextField();
        errorEmail = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        grandientPanel3 = new dashboard1.GrandientPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        NewPasswrord1 = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JLabel();
        errorPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        grandientPanel4 = new dashboard1.GrandientPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        Address2 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        Address1 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        Address3 = new javax.swing.JLabel();
        grandientPanel5 = new dashboard1.GrandientPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        NewPhone = new javax.swing.JLabel();
        InputPhone = new javax.swing.JTextField();
        errorPhoneNumber = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        grandientPanel7 = new dashboard1.GrandientPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        grandientPanel6 = new dashboard1.GrandientPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenu.setColorEnd(new java.awt.Color(0, 204, 204));
        mainMenu.setColorStart(new java.awt.Color(204, 0, 240));
        mainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/298756_dashboard_icon.png")); // NOI18N
        Dashboard.setText("    Account Dashboaed");
        Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        mainMenu.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, 63));

        Withdraw.setBackground(new java.awt.Color(255, 255, 255));
        Withdraw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Withdraw.setForeground(new java.awt.Color(255, 255, 255));
        Withdraw.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Money-2-icon.png")); // NOI18N
        Withdraw.setText("            Withdraw");
        Withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WithdrawMouseClicked(evt);
            }
        });
        mainMenu.add(Withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 260, 50));

        Deposite.setBackground(new java.awt.Color(255, 255, 255));
        Deposite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deposite.setForeground(new java.awt.Color(255, 255, 255));
        Deposite.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/4824394-200.png")); // NOI18N
        Deposite.setText("           Deposite");
        Deposite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Deposite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositeMouseClicked(evt);
            }
        });
        mainMenu.add(Deposite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 50));

        Loan.setBackground(new java.awt.Color(255, 255, 255));
        Loan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Loan.setForeground(new java.awt.Color(255, 255, 255));
        Loan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/5253089.png")); // NOI18N
        Loan.setText("               Loan");
        Loan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoanMouseClicked(evt);
            }
        });
        mainMenu.add(Loan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, 60));

        DeleteAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteAccount.setForeground(new java.awt.Color(255, 255, 255));
        DeleteAccount.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Delete.png")); // NOI18N
        DeleteAccount.setText("         Delete Account");
        DeleteAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteAccountMouseClicked(evt);
            }
        });
        mainMenu.add(DeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 270, 70));

        ProfileName.setBackground(new java.awt.Color(255, 255, 255));
        ProfileName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProfileName.setForeground(new java.awt.Color(255, 255, 255));
        ProfileName.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/AccountImage.png")); // NOI18N
        mainMenu.add(ProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 60));

        UpdateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateAccount.setForeground(new java.awt.Color(255, 255, 255));
        UpdateAccount.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Update.png")); // NOI18N
        UpdateAccount.setText("        Update Account");
        UpdateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateAccountMouseClicked(evt);
            }
        });
        mainMenu.add(UpdateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 250, 60));

        subPanel.setBackground(new java.awt.Color(255, 255, 255));
        subPanel.setOpaque(false);
        subPanel.setLayout(new javax.swing.BoxLayout(subPanel, javax.swing.BoxLayout.Y_AXIS));

        UpdateEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateEmail.setForeground(new java.awt.Color(255, 255, 255));
        UpdateEmail.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/EMaail.png")); // NOI18N
        UpdateEmail.setText("Update Email");
        UpdateEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateEmailMouseClicked(evt);
            }
        });
        subPanel.add(UpdateEmail);

        UpdatePassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdatePassword.setForeground(new java.awt.Color(255, 255, 255));
        UpdatePassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Pass.png")); // NOI18N
        UpdatePassword.setText("Udpate Password");
        UpdatePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdatePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatePasswordMouseClicked(evt);
            }
        });
        subPanel.add(UpdatePassword);

        UpdateAdress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateAdress.setForeground(new java.awt.Color(255, 255, 255));
        UpdateAdress.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images\\Addr.png")); // NOI18N
        UpdateAdress.setText("Update Address");
        UpdateAdress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateAdress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateAdressMouseClicked(evt);
            }
        });
        subPanel.add(UpdateAdress);

        UpdatePhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdatePhone.setForeground(new java.awt.Color(255, 255, 255));
        UpdatePhone.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/change-mobile-number-2.png")); // NOI18N
        UpdatePhone.setText("Update Phone number");
        UpdatePhone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdatePhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatePhoneMouseClicked(evt);
            }
        });
        subPanel.add(UpdatePhone);

        mainMenu.add(subPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 0));

        getContentPane().add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 840));

        grandientPanel11.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel11.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/53620-200.png")); // NOI18N
        jLabel11.setText("   Maze Bank Managment System");
        grandientPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 434, 70));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/log-out-icon-2048x2048-cru8zabe.png")); // NOI18N
        jLabel7.setText("LOGOUT");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        grandientPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 0, 250, 70));

        getContentPane().add(grandientPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        MainPanel.setOpaque(false);
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1240, 490));

        TransactionHistory.setBackground(new java.awt.Color(255, 255, 255));
        TransactionHistory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TransactionHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/trans.png")); // NOI18N
        TransactionHistory.setText("Transactions History");
        jPanel3.add(TransactionHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 330, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images\\Personal.png")); // NOI18N
        jLabel10.setText(" Personal Informations ");
        jLabel10.setOpaque(true);
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 50));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Blue Email.png")); // NOI18N
        jPanel4.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 60));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Blue password.png")); // NOI18N
        jPanel4.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, 50));

        Phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Phone.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/phone-png-3.png")); // NOI18N
        jPanel4.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, -1));

        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 470, 50));

        DOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/DataOfBlue.png")); // NOI18N
        jPanel4.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 240, 50));

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gender.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/GnderPender.png")); // NOI18N
        jPanel4.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 170, 50));

        ShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordMouseClicked(evt);
            }
        });
        jPanel4.add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 30));

        HidePassword.setText("jLabel3");
        HidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HidePasswordMouseClicked(evt);
            }
        });
        jPanel4.add(HidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 30));

        JD2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JD2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/date-time-circled-icon-vector-7357879.jpg")); // NOI18N
        JD2.setText("Joined Date : 4/30/20204");
        jPanel4.add(JD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 260, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/imageeree.png")); // NOI18N
        jLabel9.setText(" Account Informations");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        AccountBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountBalance.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Screenshot (655).png")); // NOI18N
        jPanel1.add(AccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 320, 40));

        AccountNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountNumber.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/account-number-8.png")); // NOI18N
        jPanel1.add(AccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, 50));

        AccountType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountType.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Saving.png")); // NOI18N
        AccountType.setText("Account Type : Saving");
        jPanel1.add(AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 50));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 410, 300));

        MainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1860, 1180));

        Main.addTab("tab1", MainPanel);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Amount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Amount.setForeground(new java.awt.Color(51, 204, 255));
        Amount.setText("Amount");
        jPanel13.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 190, 20));

        InputAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        InputAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAmountActionPerformed(evt);
            }
        });
        InputAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputAmountKeyReleased(evt);
            }
        });
        jPanel13.add(InputAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 570, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setText("                                                DEPOSITE");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 760, 90));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Depo.png")); // NOI18N
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 530, 680));

        grandientPanel1.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel1.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                                  SUBMIT");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        grandientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jPanel13.add(grandientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 570, 50));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1260, 850));

        Main.addTab("tab2", jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Amount1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Amount1.setForeground(new java.awt.Color(51, 204, 255));
        Amount1.setText("Amount");
        jPanel16.add(Amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 190, 20));

        InputAmount1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        InputAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAmount1ActionPerformed(evt);
            }
        });
        InputAmount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InputAmount1KeyPressed(evt);
            }
        });
        jPanel16.add(InputAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 550, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 51, 51));
        jPanel16.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 530, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel47.setText("                                                WITHDRAW");
        jPanel16.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 760, 90));

        jLabel48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images\\Withdraw.png")); // NOI18N
        jPanel16.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 530, 590));

        grandientPanel2.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel2.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                                  SUBMIT");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        grandientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jPanel16.add(grandientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 570, 50));

        jPanel6.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1720, 850));

        Main.addTab("tab3", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel54.setText("                                             LOANS CALCULATION");
        jPanel14.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 760, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/9196974.png")); // NOI18N
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 530, 830));

        LoanL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoanL.setForeground(new java.awt.Color(51, 204, 255));
        LoanL.setText("Enter Loan Term (Payments)");
        jPanel14.add(LoanL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 270, 30));

        Loan1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Loan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Loan1KeyReleased(evt);
            }
        });
        jPanel14.add(Loan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 560, 30));

        Lona2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Lona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lona2ActionPerformed(evt);
            }
        });
        Lona2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Lona2KeyReleased(evt);
            }
        });
        jPanel14.add(Lona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 550, 30));

        LoanLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoanLabel.setForeground(new java.awt.Color(51, 204, 255));
        LoanLabel.setText("Enter Loan Amount");
        jPanel14.add(LoanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 240, 20));

        grandientPanel8.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel8.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("                                                     CACULATE");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        grandientPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 50));

        jPanel14.add(grandientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 600, 50));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 920));

        Main.addTab("tab4", jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewEmail.setForeground(new java.awt.Color(51, 204, 255));
        NewEmail.setText("NEW EMAIL");
        jPanel17.add(NewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 190, 20));

        InputNewEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        InputNewEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputNewEmailKeyReleased(evt);
            }
        });
        jPanel17.add(InputNewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 550, 20));

        errorEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorEmail.setForeground(new java.awt.Color(255, 51, 51));
        jPanel17.add(errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 310, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel52.setText("                                                UPDATE EMAIL");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 760, 80));

        jLabel53.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/BLUEEMAIL.png")); // NOI18N
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 540, 590));

        grandientPanel3.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel3.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                 UPDATE");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        grandientPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jPanel17.add(grandientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 570, 50));

        jPanel8.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1310, 850));

        Main.addTab("tab5", jPanel8);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewPasswrord1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewPasswrord1.setForeground(new java.awt.Color(51, 204, 255));
        NewPasswrord1.setText("ENTER NEW PASSWORD AGAIN");
        jPanel18.add(NewPasswrord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 290, 20));

        Error1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Error1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel18.add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 580, 30));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel57.setText("                                                UPDATE PASSWORD");
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 760, 90));

        jLabel58.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/NEWNEWPASS.png")); // NOI18N
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 540, 520));

        NewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewPassword.setForeground(new java.awt.Color(51, 204, 255));
        NewPassword.setText("ENTER NEW PASSWORD");
        jPanel18.add(NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 240, 20));

        errorPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorPassword.setForeground(new java.awt.Color(255, 51, 51));
        jPanel18.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 580, 30));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel18.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 570, 30));

        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        jPanel18.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 580, 20));

        grandientPanel4.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel4.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("                                                     UPDATE");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        grandientPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jPanel18.add(grandientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 600, 50));

        jPanel9.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1720, 850));

        Main.addTab("tab6", jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Address2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Address2.setForeground(new java.awt.Color(51, 204, 255));
        Address2.setText("Postal,City");
        jPanel19.add(Address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 190, 20));

        jTextField13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField13KeyReleased(evt);
            }
        });
        jPanel19.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 570, 30));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel62.setText("                                                UPDATE ADDRESS");
        jPanel19.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 760, 80));

        jLabel63.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/AAAAAAAAAAAAAAAAAAAAAAA.png")); // NOI18N
        jPanel19.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 520, 510));

        jTextField16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField16KeyReleased(evt);
            }
        });
        jPanel19.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 570, 30));

        Address1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Address1.setForeground(new java.awt.Color(51, 204, 255));
        Address1.setText("STREET ADDRESS 1");
        jPanel19.add(Address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 190, 20));

        jTextField17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField17KeyReleased(evt);
            }
        });
        jPanel19.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 570, 30));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 51, 51));
        jPanel19.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 530, 30));

        Address3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Address3.setForeground(new java.awt.Color(51, 204, 255));
        Address3.setText("STREET ADDRESS 2");
        jPanel19.add(Address3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 190, 20));

        grandientPanel5.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel5.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("                                                 UPDATE");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        grandientPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 550, 50));

        jPanel19.add(grandientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 570, 50));

        jPanel10.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1720, 850));

        Main.addTab("tab7", jPanel10);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewPhone.setForeground(new java.awt.Color(51, 204, 255));
        NewPhone.setText("NEW PHONE NUMBER");
        jPanel20.add(NewPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 305, 240, 30));

        InputPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        InputPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputPhoneKeyReleased(evt);
            }
        });
        jPanel20.add(InputPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 550, 20));

        errorPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorPhoneNumber.setForeground(new java.awt.Color(255, 51, 51));
        jPanel20.add(errorPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 550, 30));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel67.setText("                                          UPDATE PHONE NUMBER");
        jPanel20.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 760, 70));

        jLabel68.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.png")); // NOI18N
        jPanel20.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 530, 580));

        grandientPanel7.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel7.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("                                                 UPDATE");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        grandientPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        jPanel20.add(grandientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 570, 50));

        jPanel11.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1260, 850));

        Main.addTab("tab8", jPanel11);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 204, 255));
        jLabel32.setText("<html> WE HATE TO SEE YOU GO<br/>   YOU CAN ALWAYS COME BACK<br/> </html>");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 520, 100));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("Closure of All Linked Services");
        jPanel12.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 320, 50));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox2.setText("All personal data and banking history will be erased permanently.");
        jCheckBox2.setToolTipText("");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        jPanel12.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 490, 50));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox3.setText("You will not be able to retrieve any historical financial data or statements");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 550, 50));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox4.setText("Any recurring payments or direct deposits set up on this account will need to be redirected");
        jPanel12.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 650, 50));

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/DELETEAAAAAAAAAAAAAAAA.png")); // NOI18N
        jPanel12.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 530, 540));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 204, 255));
        jLabel38.setText("BY DELETING YOUR ACCOUNT YOU AGREE TO :");
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 590, 60));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel39.setText("                           DELETE ACCOUNT");
        jPanel12.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 620, 80));

        grandientPanel6.setColorEnd(new java.awt.Color(0, 204, 204));
        grandientPanel6.setColorStart(new java.awt.Color(204, 0, 204));
        grandientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                                                DELETE");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        grandientPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 570, 50));

        jPanel12.add(grandientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 610, 50));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 850));

        Main.addTab("tab9", jPanel2);

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -30, 1260, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean vis=false;
    private void InputAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAmountActionPerformed

    }//GEN-LAST:event_InputAmountActionPerformed

    private void UpdateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateAccountMouseClicked
        if(!vis){subPanel.setVisible(false); vis=true;}
        boolean isVisible = subPanel.isVisible();
        subPanel.setVisible(!isVisible);

        // Adjust components only if jPanel1 was not previously visible
        if (!isVisible) {
            subPanel.removeAll();

            // Add components with spacing
            subPanel.add(UpdateEmail);
            subPanel.add(Box.createVerticalStrut(5));  // Adds vertical spacing
            subPanel.add(UpdatePassword);
            subPanel.add(Box.createVerticalStrut(5));  // Adds vertical spacing
            subPanel.add(UpdateAdress);
            subPanel.add(Box.createVerticalStrut(5));  // Adds vertical spacing
            subPanel.add(UpdatePhone);
            subPanel.revalidate();
            subPanel.repaint();
        }
        adjustComponentPositions();
    }//GEN-LAST:event_UpdateAccountMouseClicked

    private void UpdatePhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatePhoneMouseClicked
        Main.setSelectedIndex(7);
    }//GEN-LAST:event_UpdatePhoneMouseClicked

    private void UpdateAdressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateAdressMouseClicked
        Main.setSelectedIndex(6);
    }//GEN-LAST:event_UpdateAdressMouseClicked

    private void UpdatePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatePasswordMouseClicked
        Main.setSelectedIndex(5);
    }//GEN-LAST:event_UpdatePasswordMouseClicked

    private void UpdateEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateEmailMouseClicked
        Main.setSelectedIndex(4);
    }//GEN-LAST:event_UpdateEmailMouseClicked

    private void DeleteAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMouseClicked
        Main.setSelectedIndex(8);
    }//GEN-LAST:event_DeleteAccountMouseClicked

    private void LoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoanMouseClicked
        Main.setSelectedIndex(3);
    }//GEN-LAST:event_LoanMouseClicked

    private void DepositeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeMouseClicked
        Main.setSelectedIndex(1);
    }//GEN-LAST:event_DepositeMouseClicked

    private void WithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawMouseClicked
        Main.setSelectedIndex(2);
    }//GEN-LAST:event_WithdrawMouseClicked

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        Main.setSelectedIndex(0);
        try {
            addCustomer();
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DashboardMouseClicked
    long withdrawAmount=0,depositeAmount=0;
    private void InputAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAmount1ActionPerformed

    }//GEN-LAST:event_InputAmount1ActionPerformed

    private void InputAmount1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAmount1KeyPressed
     String amountText =  InputAmount1.getText().trim(); // Trim to remove any leading/trailing spaces
    if (!amountText.isEmpty()) {
        try {
            withdrawAmount = Long.parseLong(amountText);
        } catch (NumberFormatException e) {
            // Handle the case where the string is not a valid number
            System.out.println("Invalid number format");
        }
    }
        if(withdrawAmount>BankSystem.bank.customer.getAmount()){
            jLabel45.setText("Insuffient Funds For The Transaction");
        }
    }//GEN-LAST:event_InputAmount1KeyPressed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed

    }//GEN-LAST:event_jPasswordField2ActionPerformed
    String password=null,clonePass;
    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

    }//GEN-LAST:event_jPasswordField1ActionPerformed
//    ArrayList<Object>transactions=new ArrayList<>();
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        BankSystem.bank.customer.deposit(depositeAmount);
        try {
            addRowsToTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void InputAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAmountKeyReleased
    String amountText =  InputAmount.getText().trim(); // Trim to remove any leading/trailing spaces
    if (!amountText.isEmpty()) {
        try {
            depositeAmount = Long.parseLong(amountText);
        } catch (NumberFormatException e) {
            // Handle the case where the string is not a valid number
            System.out.println("Invalid number format");
        }
    }
    }//GEN-LAST:event_InputAmountKeyReleased

    private void HidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePasswordMouseClicked
                HidePassword.setVisible(false);
                String astr = new String(new char[BankSystem.bank.customer.getPass().length()]).replace("\0", "*");
                Password.setText("Password :"+astr);
                ShowPassword.setVisible(true);
    }//GEN-LAST:event_HidePasswordMouseClicked

    private void ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordMouseClicked
                HidePassword.setVisible(true);
                Password.setText("Password: "+BankSystem.bank.systemAdmin.system.decryptPassword(
                BankSystem.bank.customer.getPass()));
                ShowPassword.setVisible(false);
    }//GEN-LAST:event_ShowPasswordMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(withdrawAmount>BankSystem.bank.customer.getAmount()){
            JOptionPane.showMessageDialog(null, "Insuffient Funds For The Transaction");
            return;
        }
        BankSystem.bank.customer.withdraw(withdrawAmount);  
        try {
            addRowsToTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            dashboard1.BankSystem.bank.serverAdmin.server.updateEmail(newEmail,BankSystem.bank.customer.getEmail());
            BankSystem.bank.customer.setEmail(newEmail);
            JOptionPane.showMessageDialog(null, "Email Updated");
            
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            password=BankSystem.bank.systemAdmin.system.encryptPassword(password);
            BankSystem.bank.serverAdmin.server.updatePass(BankSystem.bank.customer.getEmail(), password);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        ad1+=',';
        ad2+=',';
        ad1=ad1+ad2+ad3;
        System.out.println(ad1);
        try {
            BankSystem.bank.serverAdmin.server.updateAddress(ad1,BankSystem.bank.customer.getEmail());
            JOptionPane.showMessageDialog(null, "Address Updated");
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            BankSystem.bank.serverAdmin.server.delete(BankSystem.bank.customer);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked
    String newEmail=null,newPhone=null;
    String ad1=null,ad2=null,ad3=null;
    
    private void InputNewEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNewEmailKeyReleased
        newEmail=InputNewEmail.getText();
        if(!BankSystem.bank.systemAdmin.system.checkEmailFormat(newEmail)){
            errorEmail.setText("Invalid Email Format");
        }else{
           errorEmail.setText(""); 
        }
        if(InputNewEmail.getText().equals("")){
            errorEmail.setText("");
        }
    }//GEN-LAST:event_InputNewEmailKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        password=new String( jPasswordField1.getPassword());
        if(password==null){
            errorPassword.setText("");
        }
        if(!BankSystem.bank.systemAdmin.system.checkPasswordFormat(password)){
            errorPassword.setText("Weak Password Use Upper/Lower Char ,Numbers and Special Characters");
           if(password!=null && password.length()<10){
            errorPassword.setText("Your password is too short");
           }
        }
        else{
           errorPassword.setText(""); 
        }
        if(new String( jPasswordField1.getPassword()).equals("")){
            errorPassword.setText("");
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        clonePass=new String(jPasswordField2.getPassword());
        if(clonePass.equals("")){
            Error1.setText("");
        }
        if(!clonePass.equals(password)){
            Error1.setText("Your password doesn't Matches");
        }
        else{
           Error1.setText(""); 
        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jTextField17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyReleased
       ad1=jTextField17.getText();
    }//GEN-LAST:event_jTextField17KeyReleased

    private void jTextField13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyReleased
        ad2=jTextField13.getText();
    }//GEN-LAST:event_jTextField13KeyReleased

    private void jTextField16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyReleased
        ad3=jTextField16.getText();
    }//GEN-LAST:event_jTextField16KeyReleased
    String contactNumber=null;
    private void InputPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPhoneKeyReleased
        contactNumber=InputPhone.getText();
        errorPhoneNumber.setText("");
        if(!BankSystem.bank.systemAdmin.system.checkPhoneFormat(contactNumber)){
            errorPhoneNumber.setText("Invalid Phone Number Format Your Phone Should Contain 11 Numbers");
        }else{
           errorPhoneNumber.setText(""); 
        }
         if(errorPhoneNumber.getText().equals("")){
            errorPhoneNumber.setText("");
        }
    }//GEN-LAST:event_InputPhoneKeyReleased

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {
            BankSystem.bank.serverAdmin.server.updatePhone(contactNumber, BankSystem.bank.customer.getEmail());
            System.out.println(contactNumber);
            JOptionPane.showMessageDialog(null, "Phone Number Updated");
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed
    double loanTerm=0;
    private void Loan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Loan1KeyReleased
        loanTerm=Long.parseLong(Loan1.getText());
    }//GEN-LAST:event_Loan1KeyReleased
    double loanPrinciple=0;
    private void Lona2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Lona2KeyReleased
       loanPrinciple=Long.parseLong(Lona2.getText());
    }//GEN-LAST:event_Lona2KeyReleased

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        double r=(0.05/12);
        double n=loanTerm*12;
        double result=(loanPrinciple*(r)*Math.pow(r+1,n))/Math.pow(r+1,n)-1;
         JOptionPane.showMessageDialog(null, "The monthly payment is:"+(long)result+'$');
    }//GEN-LAST:event_jLabel13MouseClicked

    private void Lona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lona2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lona2ActionPerformed

private void adjustComponentPositions() {
    mainMenu.setLayout(null); // Ensuring the layout is absolute for manual adjustments

    // Calculate new height based on the visibility of jPanel1
    int heightAdjustment = subPanel.isVisible() ? subPanel.getPreferredSize().height + 20 : 0;

    // Adjust jPanel1 dimensions
    Rectangle jPanelBounds = subPanel.getBounds();
    jPanelBounds.height = heightAdjustment;
    subPanel.setBounds(jPanelBounds);

    // Adjust jLabel7 position
    Rectangle jLabel7Bounds = DeleteAccount.getBounds();
    jLabel7Bounds.y = subPanel.getY() + heightAdjustment;  // Moving jLabel7 down when jPanel1 is expanded
    DeleteAccount.setBounds(jLabel7Bounds);

    // Force jPanel2 to re-layout and repaint
    mainMenu.revalidate();
    mainMenu.repaint();
}
private void setupTableAndScroll() {
    jTable2.setShowVerticalLines(false);
    jTable2.setShowHorizontalLines(false); // Optional: hides horizontal lines as well

    jScrollPane2.setViewportView(jTable2);
    jScrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
    jScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    jScrollPane2.revalidate();
    jScrollPane2.repaint();
}
static DefaultTableModel model=new DefaultTableModel(
        null,
        new String[] {"TransactionID", "Transaction Type", "Amount", "Transaction Time"}
    );
private void addRowsToTable() throws SQLException {
//    if(dashboard1.BankSystem.bank.customer.customers == null)return;
    model.addRow(new Object[]{BankSystem.bank.customer.customers.transactionId,BankSystem.bank.customer.customers.transactionType,
    BankSystem.bank.customer.customers.amount,BankSystem.bank.customer.customers.transactionTime}); 
    BankSystem.bank.serverAdmin.server.insert_transactions(BankSystem.bank.customer.getAccountNumber()
            , BankSystem.bank.customer.customers.transactionType, BankSystem.bank.customer.customers.transactionId, BankSystem.bank.customer.customers.transactionTime, BankSystem.bank.customer.customers.amount);
//    System.out.println(BankSystem.bank.customer.customers.amount);
    jTable2.setModel(model);
    jScrollPane2.setViewportView(jTable2);
    jTable2.revalidate();
    jTable2.repaint();
}

public final void addCustomer() throws SQLException{
   AccountNumber.setText("Accounrt Number: "+BankSystem.bank.customer.getAccountNumber());
   Address.setText("Address: "+BankSystem.bank.customer.getAddress());
   AccountBalance.setText("Balance: "+Long.toString(BankSystem.bank.customer.getAmount())+'$');
   DOB.setText("Date of Birth: "+BankSystem.bank.customer.getBday());
   
   Email.setText("Email: "+BankSystem.bank.customer.getEmail());
   String astr = new String(new char[BankSystem.bank.customer.getPass().length()]).replace("\0", "*");
   Password.setText("Password: "+astr);
   
   Phone.setText("Phone Number: "+BankSystem.bank.customer.getPhone());
   Gender.setText("Gender: "+BankSystem.bank.customer.getGender());
}

private void customizeRowHeight() {
    jTable2.setRowHeight(30); // Adjust row height as needed
}
    public MainPage() throws SQLException {
    initComponents();
    customizeTableHeader();  
//    initializeTable(); // Set up the table with rows
    setupTableAndScroll();  // Adjust the JScrollPane
    customizeRowHeight();
    customizeTableCells();
    addHoverEffect(Withdraw);
    addHoverEffect(Dashboard);
    addHoverEffect(Deposite);
    addHoverEffect(DeleteAccount);
    addHoverEffect(UpdateAccount);
    addHoverEffect(Loan);
    addHoverEffect(UpdateEmail);
    addHoverEffect(UpdatePassword);
    addHoverEffect(UpdateAdress);
    addHoverEffect(UpdatePhone);
    ProfileName.setText("Welcome "+dashboard1.BankSystem.bank.customer.getName()+" "+dashboard1.BankSystem.bank.customer.getLName());
    addCustomer();
    jTable2.setModel(model);
    BankSystem.bank.serverAdmin.server.query_transactions(BankSystem.bank.customer.getAccountNumber());
//   if(dashboard1.BankSystem.bank.customer==null){return;};   
//   System.out.println(BankSystem.bank.customer.getPhone());
    jPanel4.revalidate();
    jPanel4.repaint();
    jPanel1.revalidate();
    jPanel1.repaint();
    ProfileName.repaint();
    ProfileName.revalidate();
}
   private void customizeTableHeader() {
    jTable2.getTableHeader().setBackground(new Color(204, 0, 204));  // Set a custom color
    jTable2.getTableHeader().setForeground(Color.WHITE);  // Set text color to white
    jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));  // Set the font style
    jTable2.getTableHeader().setOpaque(false);
    jTable2.getTableHeader().setPreferredSize(new Dimension(jTable2.getTableHeader().getWidth(), 35));

    jTable2.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            headerLabel.setBorder(BorderFactory.createEmptyBorder());  // Removing borders
            headerLabel.setBackground(new Color(0, 204, 204));
            headerLabel.setForeground(Color.WHITE);
            headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 14));
            headerLabel.setHorizontalAlignment(JLabel.CENTER);
            return headerLabel;
        }
    });
}
   
   private void customizeTableCells() {
    jTable2.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            
            // Default background color settings for alternating rows
            if (row % 2 == 0) {
                setBackground(new Color(240, 240, 240)); // Lighter shade for alternate rows
            } else {
                setBackground(Color.WHITE); // White background for other rows
            }
            
            // Default text color and font settings
            setForeground(Color.BLACK); // Default text color
            setFont(new Font("Segoe UI", Font.BOLD, 15)); // Font settings
            if (column == 1) { // Assuming the Transaction Type is at column index 1
                if ("Withdraw".equals(value)) {
                    setText(value.toString()); // Add minus sign for withdrawals
                    setForeground(Color.RED); // Set text color to red for withdrawals
                } else if ("Deposit".equals(value)) {
                    setText(value.toString()); // Add plus sign for deposits
                    setForeground(new Color(0, 128, 0)); // Set text color to green for deposits
                }
            }
            // Check the transaction type and format the "Amount" column
            if (column == 2) {  // Assuming the "Amount" column is at column index 2
                Object typeValue = table.getModel().getValueAt(row, 1);  // Get the transaction type from column 1
                if ("Withdraw".equals(typeValue)) {
                    setText("- " + value.toString()); // Add minus sign for withdrawals
                    setForeground(Color.RED); // Set text color to red for withdrawals
                } else if ("Deposit".equals(typeValue)) {
                    setText("+ " + value.toString()); // Add plus sign for deposits
                    setForeground(new Color(0, 128, 0)); // Set text color to green for deposits
                }
            }

            // Align text to center in certain columns if necessary
            if (column == 0 || column == 2 || column == 3) {
                setHorizontalAlignment(JLabel.CENTER); // Center alignment for ID and Time columns
            } else {
                setHorizontalAlignment(JLabel.LEFT); // Left alignment for the Transaction Type column
            }
            return this;
            
        }
    });
}
private void addHoverEffect(javax.swing.JLabel label) {
    label.setOpaque(false);
    label.setForeground(Color.WHITE); // Initial text color

    label.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            // On hover, make the label opaque and change the background color
            label.setOpaque(true);
            label.setBackground(Color.BLUE); // Solid color on hover
            label.setForeground(Color.YELLOW); // Change text color to contrast with the hover background
            label.setBorder(javax.swing.BorderFactory.createLineBorder(Color.YELLOW)); // Optional: add a border
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            // On mouse exit, revert the label to non-opaque to show the gradient again
            label.setOpaque(false);
            label.setBackground(null); // Clear any specific background color
            label.setForeground(Color.WHITE); // Revert text color
            label.setBorder(null); // Remove border if added
            label.repaint(); // Ensure the label repaints to reflect these changes
        }
    });
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountBalance;
    private javax.swing.JLabel AccountNumber;
    private javax.swing.JLabel AccountType;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel Address3;
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel Amount1;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel DeleteAccount;
    private javax.swing.JLabel Deposite;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel HidePassword;
    private javax.swing.JTextField InputAmount;
    private javax.swing.JTextField InputAmount1;
    private javax.swing.JTextField InputNewEmail;
    private javax.swing.JTextField InputPhone;
    private javax.swing.JLabel JD2;
    private javax.swing.JLabel Loan;
    private javax.swing.JTextField Loan1;
    private javax.swing.JLabel LoanL;
    private javax.swing.JLabel LoanLabel;
    private javax.swing.JTextField Lona2;
    private javax.swing.JTabbedPane Main;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NewEmail;
    private javax.swing.JLabel NewPassword;
    private javax.swing.JLabel NewPasswrord1;
    private javax.swing.JLabel NewPhone;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel ProfileName;
    private javax.swing.JLabel ShowPassword;
    private javax.swing.JLabel TransactionHistory;
    private javax.swing.JLabel UpdateAccount;
    private javax.swing.JLabel UpdateAdress;
    private javax.swing.JLabel UpdateEmail;
    private javax.swing.JLabel UpdatePassword;
    private javax.swing.JLabel UpdatePhone;
    private javax.swing.JLabel Withdraw;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel errorPhoneNumber;
    private dashboard1.GrandientPanel grandientPanel1;
    private dashboard1.GrandientPanel grandientPanel11;
    private dashboard1.GrandientPanel grandientPanel2;
    private dashboard1.GrandientPanel grandientPanel3;
    private dashboard1.GrandientPanel grandientPanel4;
    private dashboard1.GrandientPanel grandientPanel5;
    private dashboard1.GrandientPanel grandientPanel6;
    private dashboard1.GrandientPanel grandientPanel7;
    private dashboard1.GrandientPanel grandientPanel8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private dashboard1.GrandientPanel mainMenu;
    private javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
}