/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard1;
import dashboard1.BankSystem;
import dashboard1.Login;
import dashboard1.SignUp;
import dashboard1.forgotPassword;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Moemen Mohamed
 */
public class NewPassword extends javax.swing.JFrame {

    /**
     * Creates new form NewPassword
     */
    public NewPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new dashboard1.GrandientPanel();
        jPanel1 = new javax.swing.JPanel();
        NewPassword = new javax.swing.JLabel();
        jPanel22 = new dashboard1.GrandientPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        newPass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        errorPassword = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel21.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel21.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewPassword.setForeground(new java.awt.Color(51, 204, 255));
        NewPassword.setText("Enter New Password");
        jPanel1.add(NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 210, 40));

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel22.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                                          SUBMIT");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 460, 50));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 520, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 255));
        jLabel25.setText("                  SET NEW PASSWORD ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 410, 50));

        newPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newPass.setForeground(new java.awt.Color(51, 204, 255));
        newPass.setText("Enter New Password Again");
        jPanel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 220, 40));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 520, 20));

        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 510, 30));
        jPanel1.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 500, 30));
        jPanel1.add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 500, 30));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 720, 460));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Understanding Customers And Make their life Easy With One Click");
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 780, 70));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/53620-200.png")); // NOI18N
        jLabel2.setText("    Maze Bank");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 330, 90));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("       Banking Software");
        jPanel21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 280, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/Bankeeeeeeeees.png")); // NOI18N
        jPanel21.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 550, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed
    String password=null,clonePass=null;
    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        password=new String( Password.getPassword());
        if(password==null){
            errorPassword.setText("");
        }
        if(!BankSystem.bank.systemAdmin.system.checkPasswordFormat(password)){
            errorPassword.setText("Weak Password Use Upper/Lower Char ,Numbers and Special Characters");
           if(password!=null && password.length()<10){
            errorPassword.setText("Your password is too short");
           }
        }
        else{
           errorPassword.setText(""); 
        }
        if(new String( Password.getPassword()).equals("")){
            errorPassword.setText("");
        }
    }//GEN-LAST:event_PasswordKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        clonePass=new String(jPasswordField1.getPassword());
        if(clonePass==null){
            Error1.setText("");
        }
        if(clonePass!=password){
            Error1.setText("Your password doesn't Matches");
        }
        else{
           Error1.setText(""); 
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            password=BankSystem.bank.systemAdmin.system.encryptPassword(password);
            dashboard1.BankSystem.bank.serverAdmin.server.updatePass(forgotPassword.client.getEmail(),password);
            JOptionPane.showMessageDialog(null, "Thank You, Login Again With New Password");
        } catch (SQLException ex) {
            Logger.getLogger(NewPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewPassword().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel NewPassword;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private dashboard1.GrandientPanel jPanel21;
    private dashboard1.GrandientPanel jPanel22;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel newPass;
    // End of variables declaration//GEN-END:variables
}
