/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard1;
import dashboard1.BankSystem;
import dashboard1.BankSystem.Bank;
import static dashboard1.BankSystem.security;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Moemen Mohamed
 */
public class SignUp extends javax.swing.JFrame {
    static String fName, lName, email = null, password="", dob1= null,dob2=null,dob3=null, 
            address1 = null,address2=null,address3=null, gender=null, contactNumber = null;
    static long amount;
    static String sq1=BankSystem.security[0],sqa1=null,sq2=BankSystem.security[1],sqa2=null, sq3=BankSystem.security[2],sqa3=null;
    /**
     * Creates new form SignUp
     */
    public SignUp() throws SQLException {
        initComponents();
        SetAddressFormat();
        SetDOBFormat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new dashboard1.GrandientPanel();
        jPanel1 = new javax.swing.JPanel();
        inputLName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        errorAddress = new javax.swing.JLabel();
        LableLname = new javax.swing.JLabel();
        Address2 = new javax.swing.JLabel();
        inputFname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        errorFname = new javax.swing.JLabel();
        DOB3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        errorEmail = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        errorPassword = new javax.swing.JLabel();
        DOB1 = new javax.swing.JTextField();
        Address1 = new javax.swing.JTextField();
        errorPhoneNumber = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        DOB2 = new javax.swing.JTextField();
        errorDOB = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Address3 = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jPanel22 = new dashboard1.GrandientPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel21.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputLName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        inputLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLNameActionPerformed(evt);
            }
        });
        inputLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputLNameKeyPressed(evt);
            }
        });
        jPanel1.add(inputLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 170, 30));

        LastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 170, 10));

        errorAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorAddress.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 270, 20));

        LableLname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LableLname.setForeground(new java.awt.Color(51, 204, 255));
        LableLname.setText("LastName");
        jPanel1.add(LableLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        Address2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address2.setForeground(new java.awt.Color(51, 204, 255));
        Address2.setText("Address");
        jPanel1.add(Address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 220, 20));

        inputFname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        inputFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFnameActionPerformed(evt);
            }
        });
        inputFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputFnameKeyPressed(evt);
            }
        });
        jPanel1.add(inputFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setText("FirstNmae");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 80, -1));

        errorFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorFname.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        DOB3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        DOB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB3ActionPerformed(evt);
            }
        });
        DOB3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DOB3KeyPressed(evt);
            }
        });
        jPanel1.add(DOB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 90, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, 20));

        inputEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        inputEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputEmailKeyReleased(evt);
            }
        });
        jPanel1.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 470, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 255));
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 80, 30));

        errorEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorEmail.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 460, 20));

        inputPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        inputPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPhoneActionPerformed(evt);
            }
        });
        inputPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPhoneKeyPressed(evt);
            }
        });
        jPanel1.add(inputPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 470, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setText("Phone Number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 20));

        errorPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorPassword.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 460, 30));

        DOB1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        DOB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB1ActionPerformed(evt);
            }
        });
        DOB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DOB1KeyPressed(evt);
            }
        });
        jPanel1.add(DOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 90, 20));

        Address1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address1ActionPerformed(evt);
            }
        });
        Address1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Address1KeyPressed(evt);
            }
        });
        jPanel1.add(Address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 470, 20));

        errorPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorPhoneNumber.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 470, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 255));
        jLabel17.setText("Date of Birth");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 110, 20));

        DOB2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        DOB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB2ActionPerformed(evt);
            }
        });
        DOB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DOB2KeyPressed(evt);
            }
        });
        jPanel1.add(DOB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, 20));

        errorDOB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorDOB.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 290, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 255));
        jLabel19.setText("Amount You wish to open your account with");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 330, 20));

        Amount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });
        Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AmountKeyPressed(evt);
            }
        });
        jPanel1.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 470, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 240, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 255));
        jLabel21.setText("Address");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 200, 20));

        Address3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Address3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address3ActionPerformed(evt);
            }
        });
        Address3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Address3KeyPressed(evt);
            }
        });
        jPanel1.add(Address3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 470, 20));

        Address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddressKeyPressed(evt);
            }
        });
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 470, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 204, 255));
        jLabel23.setText("Address");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 200, 20));

        Male.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        jPanel1.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 90, -1));

        Female.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        jPanel1.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 100, 20));

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setColorEnd(new java.awt.Color(0, 204, 204));
        jPanel22.setColorStart(new java.awt.Color(204, 0, 204));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                       SIGN UP");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 50));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 330, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 255));
        jLabel25.setText("                 SIGN UP");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 240, 50));

        inputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        inputPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 470, 30));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 680, 740));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html> Understanding Customers <br/> And Make their life Easy With One Click </br> </html>");
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 460, 100));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images/53620-200.png")); // NOI18N
        jLabel2.setText("     Maze Bank");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("       Banking Software");
        jPanel21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moemen Mohamed\\Documents\\NetBeansProjects\\Dashboard1\\test\\Images\\Bankeeeeeeeees.png")); // NOI18N
        jPanel21.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 530, 500));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -1, 1420, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DOB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB3ActionPerformed

    private void inputPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPhoneActionPerformed

    private void DOB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB1ActionPerformed

    private void Address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address1ActionPerformed

    private void DOB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB2ActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void Address3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address3ActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        if(gender!=null)return;
        gender=Female.getText();
    }//GEN-LAST:event_FemaleActionPerformed

    private void inputLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLNameActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFnameActionPerformed

    }//GEN-LAST:event_inputFnameActionPerformed

    private void inputFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFnameKeyPressed
       fName=inputFname.getText();
    }//GEN-LAST:event_inputFnameKeyPressed
   static boolean FlagFname=false,FlagLname=false,FlagEmail=false,FlagPassword=false,
            FlagAddress=false,FlagPhone=false,FlagDOB=false,Flaganmount=false,FlagGender=false;
    private void inputLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputLNameKeyPressed
       lName=inputLName.getText();
    }//GEN-LAST:event_inputLNameKeyPressed

    private void inputPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPasswordKeyPressed
        password=new String(inputPassword.getPassword());
        if(password==null){
            errorPassword.setText("");
        }
        if(!BankSystem.bank.systemAdmin.system.checkPasswordFormat(password)){
            errorPassword.setText("Weak Password Use Upper/Lower Char ,Numbers and Special Characters");
           if(password!=null && password.length()<10){
            errorPassword.setText("Your password is too short");
           }
        }
        else{
           errorPassword.setText(""); 
        }
        if(new String(inputPassword.getPassword()).equals("")){
            errorPassword.setText("");
        }
    }//GEN-LAST:event_inputPasswordKeyPressed

    private void inputPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPhoneKeyPressed
        contactNumber=inputPhone.getText();
        errorPhoneNumber.setText("");
        if(!BankSystem.bank.systemAdmin.system.checkPhoneFormat(contactNumber)){
            errorPhoneNumber.setText("Invalid Phone Number Format Your Phone Should Contain 11 Numbers");
        }else{
           errorPhoneNumber.setText(""); 
        }
         if(errorPhoneNumber.getText().equals("")){
            errorPhoneNumber.setText("");
        }
    }//GEN-LAST:event_inputPhoneKeyPressed

    private void DOB2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DOB2KeyPressed
        dob2=DOB2.getText();
    }//GEN-LAST:event_DOB2KeyPressed

    private void DOB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DOB1KeyPressed
        dob1=DOB1.getText();
    }//GEN-LAST:event_DOB1KeyPressed

    private void DOB3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DOB3KeyPressed

        dob3=DOB3.getText();
        SetDOBFormat();
       
    }//GEN-LAST:event_DOB3KeyPressed

    private void AmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyPressed
    String amountText = Amount.getText().trim(); // Trim to remove any leading/trailing spaces
    if (!amountText.isEmpty()) {
        try {
            amount = Long.parseLong(amountText);
        } catch (NumberFormatException e) {
            // Handle the case where the string is not a valid number
            System.out.println("Invalid number format");
        }
    }
    }//GEN-LAST:event_AmountKeyPressed

    private void AddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressKeyPressed
        address1=Address.getText();
    }//GEN-LAST:event_AddressKeyPressed

    private void Address1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Address1KeyPressed
        address2=Address1.getText();
    }//GEN-LAST:event_Address1KeyPressed

    private void Address3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Address3KeyPressed
        address3=Address3.getText();
        SetAddressFormat();
    }//GEN-LAST:event_Address3KeyPressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

      JOptionPane.showMessageDialog(null, "Thank You For Registering.");
      
      setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new appendSecurity().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_jLabel10MouseClicked

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        gender=Male.getText();
        
    }//GEN-LAST:event_MaleActionPerformed

    private void inputEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEmailKeyReleased
        email=inputEmail.getText();
        if(!BankSystem.bank.systemAdmin.system.checkEmailFormat(email)){
            errorEmail.setText("Invalid Email Format");
        }else{
           errorEmail.setText(""); 
        }
        if(inputEmail.getText().equals("")){
            errorEmail.setText("");
        }
    }//GEN-LAST:event_inputEmailKeyReleased

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none
    static String DOB="",Add="";
    private void SetDOBFormat(){
        DOB=dob1+'/';
        DOB+=dob2+'/';
        DOB+=dob3;
        
    }
    private void SetAddressFormat(){
        String Address=null;
        Add=address1+',';
        Add+=address2+',';
        Add+=address3;
    
   }
    public void signup() throws SQLException{
        password = BankSystem.bank.systemAdmin.system.encryptPassword(password);
        BankSystem.bank.customer = new BankSystem().new Client(fName, lName, Add, contactNumber, email, password, DOB, gender, amount,sqa1,sqa2,sqa3,0);
        BankSystem.bank.customer.setGenerate(); 
        System.out.println(fName);
        System.out.println(lName);
        System.out.println(Add);
        System.out.println(contactNumber);
        System.out.println(email);
        System.out.println(password);
        System.out.println(DOB);
        System.out.println(gender);
        System.out.println(amount);
        System.out.println(sqa1);
        System.out.println(sqa2);
        System.out.println(sqa3);
        
//        BankSystem.bank.serverAdmin.server.Create();
        BankSystem.bank.serverAdmin.server.insert_customers(BankSystem.bank.customer);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws SQLException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//            java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new SignUp().setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JTextField Address3;
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField DOB1;
    private javax.swing.JTextField DOB2;
    private javax.swing.JTextField DOB3;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel LableLname;
    private javax.swing.JLabel LastName;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel errorAddress;
    private javax.swing.JLabel errorDOB;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorFname;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel errorPhoneNumber;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputFname;
    private javax.swing.JTextField inputLName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private dashboard1.GrandientPanel jPanel21;
    private dashboard1.GrandientPanel jPanel22;
    // End of variables declaration//GEN-END:variables
}
